spring.application.name=news2Post

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/news2post
spring.datasource.username=news2post
spring.datasource.password=news2post
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080



app.ai.provider=groq
app.groq.apiKey=${GROQ_API_KEY}
app.groq.model=llama-3.1-8b-instant

