spring.application.name=news2Post

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}



spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}


app.ai.provider=groq
app.groq.apiKey=${GROQ_API_KEY}
app.groq.model=llama-3.1-8b-instant




